### ISSUE TITLE
Dockerized backend

### ISSUE THREAD

**Issue by SuhailAhmedVelorum** [AshiqAbdulkhader/Simucode#1]
Dockerize the FastAPI app to be reachable on localhost:<port>.

**Comment by fisher60** [comment]
Hello, which parts of this project need to be dockerized exactly? I could probably do this.

**Comment by AshiqAbdulkhader** [comment]
> Hello, which parts of this project need to be dockerized exactly? I could probably do this.

The compiler Backend
